apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx-deployment
  labels:
    app: react-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-nginx
  template:
    metadata:
      labels:
        app: react-nginx
    spec:
      containers:
      - name: react-nginx
        image: react-nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-nginx-service
spec:
  type: NodePort
  selector:
    app: react-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
